spring.application.name=inventory-system

spring.datasource.url=${DB_URL:jdbc:mysql://avnadmin:AVNS_g4jSgi3X50UBru92ZGx@mysql-29a214c1-kagamealain2050-0dfb.c.aivencloud.com:27468/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASS:AVNS_g4jSgi3X50UBru92ZGx}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8083}
